services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  _instanceof:
    Symfony\Component\Console\Command\Command:
      tags: ['console.command']

  Cordon\CodeNameConverterBundle\:
    resource: '../../src'
    exclude: '../../src/{DependencyInjection,Entity,Tests}'

